var es = require("event-stream");
var http = require("http");
var Live = require("../live-edit");
var util = require("gulp-util");

function LiveServer() {
	this.live = new Live();
}

LiveServer.prototype.start = function(options) {
	this.live.start(options);
};

LiveServer.prototype.edited = function(filepath) {
	this.live.onFileChange(filepath);
};

LiveServer.prototype.close = function() {
	this.live.close();
};

var server = new LiveServer();

module.exports = {
	start: function(options) {
		return server.start(options);
	},
	edited: function() {
		console.log('edited');

		var files = Array.prototype.slice.call(arguments);
		if (files[files.length - 1] === 'function') done = files.pop();
		done = typeof done === 'function' ? done : function() {};
		files.forEach(function(file) {
			server.edited(file.path);
			done();
		});
	}
};

// ---
// generated by coffee-script 1.9.2
